package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Binhchon generated by hbm2java
 */
@Entity
@Table(name = "binhchon", catalog = "phuong_perfume")
public class BinhChon implements java.io.Serializable {

	private Integer id;
	private SanPham sanpham;
	private String ten;
	private String email;
	private int diem;

	public BinhChon() {
	}

	public BinhChon(SanPham sanpham, String ten, String email, int diem) {
		this.sanpham = sanpham;
		this.ten = ten;
		this.email = email;
		this.diem = diem;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sanpham", nullable = false)
	public SanPham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(SanPham sanpham) {
		this.sanpham = sanpham;
	}

	@Column(name = "ten", nullable = false, length = 200)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "diem", nullable = false)
	public int getDiem() {
		return this.diem;
	}

	public void setDiem(int diem) {
		this.diem = diem;
	}

}
