package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietdonhang generated by hbm2java
 */
@Entity
@Table(name = "chitietdonhang", catalog = "phuong_perfume")
public class ChiTietDonHang implements java.io.Serializable {

	private Integer id;
	private DonHang donhang;
	private SanPham sanpham;
	private int soluong;

	public ChiTietDonHang() {
	}

	public ChiTietDonHang(DonHang donhang, SanPham sanpham, int soluong) {
		this.donhang = donhang;
		this.sanpham = sanpham;
		this.soluong = soluong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_donhang", nullable = false)
	public DonHang getDonhang() {
		return this.donhang;
	}

	public void setDonhang(DonHang donhang) {
		this.donhang = donhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sanpham", nullable = false)
	public SanPham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(SanPham sanpham) {
		this.sanpham = sanpham;
	}

	@Column(name = "soluong", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

}
