package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donhang generated by hbm2java
 */
@Entity
@Table(name = "donhang", catalog = "phuong_perfume")
public class DonHang implements java.io.Serializable {

	private Integer id;
	private NguoiDung nguoidung;
	private TrangThaiDonHang trangthaidonhang;
	private Date ngaydathang;
	private String tennguoinhanhang;
	private String dienthoainguoinhan;
	private String diachigiaohang;
	private String ghichu;
	private byte thanhtoan;
	private Set<ChiTietDonHang> chitietdonhangs = new HashSet<ChiTietDonHang>(0);

	public DonHang() {
	}

	public DonHang(NguoiDung nguoidung, TrangThaiDonHang trangthaidonhang, Date ngaydathang, String tennguoinhanhang,
			String dienthoainguoinhan, String diachigiaohang, byte thanhtoan) {
		this.nguoidung = nguoidung;
		this.trangthaidonhang = trangthaidonhang;
		this.ngaydathang = ngaydathang;
		this.tennguoinhanhang = tennguoinhanhang;
		this.dienthoainguoinhan = dienthoainguoinhan;
		this.diachigiaohang = diachigiaohang;
		this.thanhtoan = thanhtoan;
	}

	public DonHang(NguoiDung nguoidung, TrangThaiDonHang trangthaidonhang, Date ngaydathang, String tennguoinhanhang,
			String dienthoainguoinhan, String diachigiaohang, String ghichu, byte thanhtoan,
			Set<ChiTietDonHang> chitietdonhangs) {
		this.nguoidung = nguoidung;
		this.trangthaidonhang = trangthaidonhang;
		this.ngaydathang = ngaydathang;
		this.tennguoinhanhang = tennguoinhanhang;
		this.dienthoainguoinhan = dienthoainguoinhan;
		this.diachigiaohang = diachigiaohang;
		this.ghichu = ghichu;
		this.thanhtoan = thanhtoan;
		this.chitietdonhangs = chitietdonhangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_khachhang", nullable = false)
	public NguoiDung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(NguoiDung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_trangthai", nullable = false)
	public TrangThaiDonHang getTrangthaidonhang() {
		return this.trangthaidonhang;
	}

	public void setTrangthaidonhang(TrangThaiDonHang trangthaidonhang) {
		this.trangthaidonhang = trangthaidonhang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaydathang", nullable = false, length = 10)
	public Date getNgaydathang() {
		return this.ngaydathang;
	}

	public void setNgaydathang(Date ngaydathang) {
		this.ngaydathang = ngaydathang;
	}

	@Column(name = "tennguoinhanhang", nullable = false, length = 200)
	public String getTennguoinhanhang() {
		return this.tennguoinhanhang;
	}

	public void setTennguoinhanhang(String tennguoinhanhang) {
		this.tennguoinhanhang = tennguoinhanhang;
	}

	@Column(name = "dienthoainguoinhan", nullable = false, length = 20)
	public String getDienthoainguoinhan() {
		return this.dienthoainguoinhan;
	}

	public void setDienthoainguoinhan(String dienthoainguoinhan) {
		this.dienthoainguoinhan = dienthoainguoinhan;
	}

	@Column(name = "diachigiaohang", nullable = false, length = 300)
	public String getDiachigiaohang() {
		return this.diachigiaohang;
	}

	public void setDiachigiaohang(String diachigiaohang) {
		this.diachigiaohang = diachigiaohang;
	}

	@Column(name = "ghichu", length = 65535)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "thanhtoan", nullable = false)
	public byte getThanhtoan() {
		return this.thanhtoan;
	}

	public void setThanhtoan(byte thanhtoan) {
		this.thanhtoan = thanhtoan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donhang")
	public Set<ChiTietDonHang> getChitietdonhangs() {
		return this.chitietdonhangs;
	}

	public void setChitietdonhangs(Set<ChiTietDonHang> chitietdonhangs) {
		this.chitietdonhangs = chitietdonhangs;
	}

}
