package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loai generated by hbm2java
 */
@Entity
@Table(name = "loai", catalog = "phuong_perfume")
public class Loai implements java.io.Serializable {

	private Integer id;
	private String tenloai;
	private Set<SanPham> sanphams = new HashSet<SanPham>(0);

	public Loai() {
	}

	public Loai(String tenloai) {
		this.tenloai = tenloai;
	}

	public Loai(String tenloai, Set<SanPham> sanphams) {
		this.tenloai = tenloai;
		this.sanphams = sanphams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tenloai", nullable = false, length = 200)
	public String getTenloai() {
		return this.tenloai;
	}

	public void setTenloai(String tenloai) {
		this.tenloai = tenloai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loai")
	public Set<SanPham> getSanphams() {
		return this.sanphams;
	}

	public void setSanphams(Set<SanPham> sanphams) {
		this.sanphams = sanphams;
	}

}
