package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name = "nguoidung", catalog = "phuong_perfume")
public class NguoiDung implements java.io.Serializable {

	private Integer id;
	private VaiTro vaitro;
	private String email;
	private String password;
	private String hoten;
	private String diachi;
	private String dtdd;
	private Set<DonHang> donhangs = new HashSet<DonHang>(0);

	public NguoiDung() {
	}

	public NguoiDung(VaiTro vaitro, String email, String password, String hoten, String diachi, String dtdd) {
		this.vaitro = vaitro;
		this.email = email;
		this.password = password;
		this.hoten = hoten;
		this.diachi = diachi;
		this.dtdd = dtdd;
	}

	public NguoiDung(VaiTro vaitro, String email, String password, String hoten, String diachi, String dtdd,
			Set<DonHang> donhangs) {
		this.vaitro = vaitro;
		this.email = email;
		this.password = password;
		this.hoten = hoten;
		this.diachi = diachi;
		this.dtdd = dtdd;
		this.donhangs = donhangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_vaitro", nullable = false)
	public VaiTro getVaitro() {
		return this.vaitro;
	}

	public void setVaitro(VaiTro vaitro) {
		this.vaitro = vaitro;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "hoten", nullable = false, length = 200)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "diachi", nullable = false, length = 300)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "dtdd", nullable = false, length = 20)
	public String getDtdd() {
		return this.dtdd;
	}

	public void setDtdd(String dtdd) {
		this.dtdd = dtdd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nguoidung")
	public Set<DonHang> getDonhangs() {
		return this.donhangs;
	}

	public void setDonhangs(Set<DonHang> donhangs) {
		this.donhangs = donhangs;
	}

}
