package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quangcao generated by hbm2java
 */
@Entity
@Table(name = "quangcao", catalog = "phuong_perfume")
public class QuangCao implements java.io.Serializable {

	private Integer id;
	private String hinhanh;
	private String thongdiep;
	private String thongtinchitiet;
	private Date ngaydang;

	public QuangCao() {
	}

	public QuangCao(String hinhanh, String thongdiep) {
		this.hinhanh = hinhanh;
		this.thongdiep = thongdiep;
	}

	public QuangCao(String hinhanh, String thongdiep, String thongtinchitiet, Date ngaydang) {
		this.hinhanh = hinhanh;
		this.thongdiep = thongdiep;
		this.thongtinchitiet = thongtinchitiet;
		this.ngaydang = ngaydang;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "hinhanh", nullable = false, length = 200)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "thongdiep", nullable = false, length = 300)
	public String getThongdiep() {
		return this.thongdiep;
	}

	public void setThongdiep(String thongdiep) {
		this.thongdiep = thongdiep;
	}

	@Column(name = "thongtinchitiet", length = 65535)
	public String getThongtinchitiet() {
		return this.thongtinchitiet;
	}

	public void setThongtinchitiet(String thongtinchitiet) {
		this.thongtinchitiet = thongtinchitiet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaydang", length = 10)
	public Date getNgaydang() {
		return this.ngaydang;
	}

	public void setNgaydang(Date ngaydang) {
		this.ngaydang = ngaydang;
	}

}
