package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name = "sanpham", catalog = "phuong_perfume")
public class SanPham implements java.io.Serializable {

	private Integer id;
	private Loai loai;
	private ThuongHieu thuonghieu;
	private String tensanpham;
	private String mota;
	private String hinhanh;
	private double dongia;
	private Double dongiaKm;
	private int soluong;
	private Date ngaytao;
	private int hienthi;
	private Set<ChiTietDonHang> chitietdonhangs = new HashSet<ChiTietDonHang>(0);
	private Set<BinhChon> binhchons = new HashSet<BinhChon>(0);

	public SanPham() {
	}

	public SanPham(Loai loai, ThuongHieu thuonghieu, String tensanpham, String hinhanh, double dongia, int soluong,
			Date ngaytao, int hienthi) {
		this.loai = loai;
		this.thuonghieu = thuonghieu;
		this.tensanpham = tensanpham;
		this.hinhanh = hinhanh;
		this.dongia = dongia;
		this.soluong = soluong;
		this.ngaytao = ngaytao;
		this.hienthi = hienthi;
	}

	public SanPham(Loai loai, ThuongHieu thuonghieu, String tensanpham, String mota, String hinhanh, double dongia,
			Double dongiaKm, int soluong, Date ngaytao, int hienthi, Set<ChiTietDonHang> chitietdonhangs,
			Set<BinhChon> binhchons) {
		this.loai = loai;
		this.thuonghieu = thuonghieu;
		this.tensanpham = tensanpham;
		this.mota = mota;
		this.hinhanh = hinhanh;
		this.dongia = dongia;
		this.dongiaKm = dongiaKm;
		this.soluong = soluong;
		this.ngaytao = ngaytao;
		this.hienthi = hienthi;
		this.chitietdonhangs = chitietdonhangs;
		this.binhchons = binhchons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_loai", nullable = false)
	public Loai getLoai() {
		return this.loai;
	}

	public void setLoai(Loai loai) {
		this.loai = loai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_thuonghieu", nullable = false)
	public ThuongHieu getThuonghieu() {
		return this.thuonghieu;
	}

	public void setThuonghieu(ThuongHieu thuonghieu) {
		this.thuonghieu = thuonghieu;
	}

	@Column(name = "tensanpham", nullable = false, length = 300)
	public String getTensanpham() {
		return this.tensanpham;
	}

	public void setTensanpham(String tensanpham) {
		this.tensanpham = tensanpham;
	}

	@Column(name = "mota", length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "hinhanh", nullable = false, length = 300)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "dongia", nullable = false, precision = 22, scale = 0)
	public double getDongia() {
		return this.dongia;
	}

	public void setDongia(double dongia) {
		this.dongia = dongia;
	}

	@Column(name = "dongiaKM", precision = 22, scale = 0)
	public Double getDongiaKm() {
		return this.dongiaKm;
	}

	public void setDongiaKm(Double dongiaKm) {
		this.dongiaKm = dongiaKm;
	}

	@Column(name = "soluong", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaytao", nullable = false, length = 10)
	public Date getNgaytao() {
		return this.ngaytao;
	}

	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

	@Column(name = "hienthi", nullable = false)
	public int getHienthi() {
		return this.hienthi;
	}

	public void setHienthi(int hienthi) {
		this.hienthi = hienthi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public Set<ChiTietDonHang> getChitietdonhangs() {
		return this.chitietdonhangs;
	}

	public void setChitietdonhangs(Set<ChiTietDonHang> chitietdonhangs) {
		this.chitietdonhangs = chitietdonhangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public Set<BinhChon> getBinhchons() {
		return this.binhchons;
	}

	public void setBinhchons(Set<BinhChon> binhchons) {
		this.binhchons = binhchons;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SanPham other = (SanPham) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
