package javaBeans;
// Generated Nov 23, 2022 6:27:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thuonghieu generated by hbm2java
 */
@Entity
@Table(name = "thuonghieu", catalog = "phuong_perfume")
public class ThuongHieu implements java.io.Serializable {

	private Integer id;
	private String tenthuonghieu;
	private String hinhanh;
	private Set<SanPham> sanphams = new HashSet<SanPham>(0);

	public ThuongHieu() {
	}

	public ThuongHieu(String tenthuonghieu, String hinhanh) {
		this.tenthuonghieu = tenthuonghieu;
		this.hinhanh = hinhanh;
	}

	public ThuongHieu(String tenthuonghieu, String hinhanh, Set<SanPham> sanphams) {
		this.tenthuonghieu = tenthuonghieu;
		this.hinhanh = hinhanh;
		this.sanphams = sanphams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tenthuonghieu", nullable = false, length = 300)
	public String getTenthuonghieu() {
		return this.tenthuonghieu;
	}

	public void setTenthuonghieu(String tenthuonghieu) {
		this.tenthuonghieu = tenthuonghieu;
	}

	@Column(name = "hinhanh", nullable = false, length = 300)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thuonghieu")
	public Set<SanPham> getSanphams() {
		return this.sanphams;
	}

	public void setSanphams(Set<SanPham> sanphams) {
		this.sanphams = sanphams;
	}

}
